import { EventEmitter } from 'events';

// Central Event Bus for the Nexa AI Protocol
class NexaEventBus extends EventEmitter {}

export const eventBus = new NexaEventBus();

// Core Event Types
export enum SystemEvents {
    SIGNAL_RECEIVED = 'SIGNAL_RECEIVED',
    MARKET_PROPOSAL_GENERATED = 'MARKET_PROPOSAL_GENERATED',
    EVALUATION_SUBMITTED = 'EVALUATION_SUBMITTED',
    MARKET_APPROVED = 'MARKET_APPROVED',
    MARKET_SUGGESTED = 'MARKET_SUGGESTED',
    MARKET_RESOLVED = 'MARKET_RESOLVED',
    DEBATE_INITIATED = 'DEBATE_INITIATED',
    DEBATE_RISK_REVIEWED = 'DEBATE_RISK_REVIEWED',
    DEBATE_COMPLIANCE_REVIEWED = 'DEBATE_COMPLIANCE_REVIEWED',
    DEBATE_ANALYST_RESPONDED = 'DEBATE_ANALYST_RESPONDED',
    DEBATE_CONCLUDED = 'DEBATE_CONCLUDED'
}
